using Content.Shared.MassMedia.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.MassMedia.Ui;

[GenerateTypedNameReferences]
public sealed partial class NewsArticleCard : Control
{
    private string? _authorMarkup;
    private TimeSpan? _publicationTime;

    public Action? OnDeletePressed;
    public Action<int>? OnDeleteCommentPressed;
    public int ArtcileNumber;

    public string? Title
    {
        get => TitleLabel.Text;
        set => TitleLabel.Text = value?.Length <= 30 ? value : $"{value?[..30]}...";
    }

    public string? Author
    {
        get => _authorMarkup;
        set
        {
            _authorMarkup = value;
            AuthorLabel.Text = _authorMarkup ?? "";
        }
    }

    public TimeSpan? PublicationTime
    {
        get => _publicationTime;
        set
        {
            _publicationTime = value;
            PublishTimeLabel.Text = value?.ToString(@"hh\:mm\:ss") ?? "";
        }
    }

    public NewsArticleCard()
    {
        RobustXamlLoader.Load(this);
        DeleteButton.OnPressed += _ => OnDeletePressed?.Invoke();
    }

    public void SetComments(List<NewsComment>? comments)
    {
        CommentsContainer.Children.Clear();
        if (comments == null || comments.Count == 0)
            return;

        for (var i = 0; i < comments.Count; i++)
        {
            var commentIndex = i;
            var comment = comments[i];

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 2, 0, 0)
            };

            var truncated = comment.Content.Length > 60 ? $"{comment.Content[..60]}..." : comment.Content;
            var info = new Label
            {
                Text = $"[{comment.Timestamp:hh\\:mm\\:ss}] {comment.Author}: {truncated}",
                HorizontalExpand = true,
                FontColorOverride = Color.FromHex("#b1b1b2")
            };
            info.AddStyleClass("LabelSmall");

            var deleteBtn = new Button
            {
                Text = Loc.GetString("news-comment-delete-button"),
                Margin = new Thickness(4, 0, 0, 0)
            };
            deleteBtn.AddStyleClass("ButtonSmall");
            deleteBtn.AddStyleClass("negative");
            deleteBtn.SetHeight = 19;
            deleteBtn.SetWidth = 52;
            deleteBtn.OnPressed += _ => OnDeleteCommentPressed?.Invoke(commentIndex);

            row.AddChild(info);
            row.AddChild(deleteBtn);
            CommentsContainer.AddChild(row);
        }
    }
}
