- type: entity
  id: ExtractGrinderMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: extract grinder machine board
  description: A machine printed circuit board for a extract grinder.
  components:
  - type: Sprite
    state: science
  - type: MachineBoard
    prototype: ExtractGrinder
    stackRequirements:
      MatterBin: 2
      Manipulator: 2
      Steel: 5