using Content.Client.Message;
using Content.Shared.MassMedia.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NewsReaderUiFragment : BoxContainer
{
    public event Action? OnNextButtonPressed;
    public event Action? OnPrevButtonPressed;
    public event Action? OnNotificationSwithPressed;
    public event Action<string>? OnPostCommentPressed;

    public NewsReaderUiFragment()
    {
        RobustXamlLoader.Load(this);

        Next.OnPressed += _ => OnNextButtonPressed?.Invoke();
        Prev.OnPressed += _ => OnPrevButtonPressed?.Invoke();
        NotificationSwitch.OnPressed += _ => OnNotificationSwithPressed?.Invoke();
        PostCommentButton.OnPressed += _ => TryPostComment();
        CommentInput.OnTextEntered += _ => TryPostComment();
    }

    private void TryPostComment()
    {
        var text = CommentInput.Text.Trim();
        if (!string.IsNullOrEmpty(text))
        {
            OnPostCommentPressed?.Invoke(text);
            CommentInput.Text = string.Empty;
        }
    }

    public void UpdateState(NewsArticle article, int targetNum, int totalNum, bool notificationOn)
    {
        PageNum.Visible = true;
        PageText.Visible = true;
        ShareTime.Visible = true;
        Author.Visible = true;
        CommentsSection.Visible = true;
        CommentInputBox.Visible = true;

        PageName.Text = article.Title;
        PageText.SetMarkupPermissive(article.Content);

        PageNum.Text = $"{targetNum}/{totalNum}";

        NotificationSwitch.Text = Loc.GetString(notificationOn ? "news-read-ui-notification-on" : "news-read-ui-notification-off");

        string shareTime = article.ShareTime.ToString(@"hh\:mm\:ss");
        ShareTime.SetMarkup(Loc.GetString("news-read-ui-time-prefix-text") + " " + shareTime);

        Author.SetMarkup(Loc.GetString("news-read-ui-author-prefix") + " " + (article.Author != null ? article.Author : Loc.GetString("news-read-ui-no-author")));

        Prev.Disabled = targetNum <= 1;
        Next.Disabled = targetNum >= totalNum;

        CommentsHeader.Text = Loc.GetString("news-comments-header");
        CommentsList.Children.Clear();

        if (article.Comments is { Count: > 0 })
        {
            NoCommentsLabel.Visible = false;
            foreach (var comment in article.Comments)
            {
                var entry = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                    Margin = new Thickness(8, 2, 8, 2)
                };

                var header = new RichTextLabel();
                header.SetMarkupPermissive($"[bold]{comment.Author}[/bold]  [color=#888888]{comment.Timestamp:hh\\:mm\\:ss}[/color]");

                var bodyMsg = new FormattedMessage();
                bodyMsg.AddText(comment.Content);
                var body = new RichTextLabel { HorizontalExpand = true };
                body.SetMessage(bodyMsg);

                entry.AddChild(header);
                entry.AddChild(body);
                CommentsList.AddChild(entry);
            }
        }
        else
        {
            NoCommentsLabel.Visible = true;
            NoCommentsLabel.Text = Loc.GetString("news-comments-empty");
        }
    }

    public void UpdateEmptyState(bool notificationOn)
    {
        PageNum.Visible = false;
        PageText.Visible = false;
        ShareTime.Visible = false;
        Author.Visible = false;
        CommentsSection.Visible = false;
        CommentInputBox.Visible = false;

        PageName.Text = Loc.GetString("news-read-ui-not-found-text");

        NotificationSwitch.Text = Loc.GetString(notificationOn ? "news-read-ui-notification-on" : "news-read-ui-notification-off");
    }
}
